export const navlinks = [
    {
        id:1,
        name:'Home',
        path:'/',
        icon:'Home'
    },
    {
        id:2,
        name:'Courses',
        path:'/courses',
        icon:'Book'
    },
    {
        id:3,
        name:'Services',
        path:'/services',
        icon:'Home'
    },
    {
        id:5,
        name:'Plan Board',
        path:'/planner',
        icon:'Home'
    },
    {
        id:6,
        name:'Todo',
        path:'/todo',
        icon:'Home'
    },{
        id:7,
        name:'Components',
        path:'/components',
        icon:'Home'
    },
    {
        id:4,
        name:'Contact',
        path:'/contact',
        icon:'Home'
    },

]